alias ls='ls --color=auto --group-directories-first'
alias la='ls -lah --color=auto --group-directories-first'
alias c='clear'
alias bye='shutdown now'
alias dots='/usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"'
alias ff='clear && fastfetch'
